name: Hugo Actions

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'static/assets/images/**'
      - 'static/assets/images/logos/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.122.0'
          extended: false

      - name: Build Site
        run: |
          cp -R exampleSite/* .
          hugo --themesDir ../ --baseURL https://aldult-live.github.io/WebStack-Hugo

      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          full_commit_message: ${{ github.event.head_commit.message }}
